# Generated by Django 5.1.6 on 2025-03-16 11:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_blog_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='customer',
            field=models.ManyToManyField(blank=True, related_name='blogs_joined', to=settings.AUTH_USER_MODEL),
        ),
    ]
